name: 'Deploy Workload Infrastructure'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform_workload:
    name: 'Deploy Workload Infrastructure using Terraform'
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_environment: ${{ github.ref_name }}
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.8.5
    
      - name: Terraform Init
        run: terraform init -backend-config="key=${{ github.ref_name }}"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            --var "environment=${{ github.ref_name }}" \
            --input=false \
            --out terraform-plan

      - name: Terraform Apply
        id: apply
        run: terraform apply terraform-plan

      - name: Terraform Destroy on Failure
        if: failure() && steps.apply.outcome == 'failure'
        run: terraform destroy -auto-approve