name: Terraform Tests

on:
  push:
    branches: ["test", "main"]
  
  pull_request:
    
      

jobs:
  terraform:
    name: Terraform Testing
    runs-on: ubuntu-latest

    env:
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.5

      # Initialize Terraform
      - name: Terraform Init with Remote Backend
        run: |
          terraform init \
            -backend-config=backend-config-test.conf \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      # Validate Terraform syntax
      - name: Terraform Validate
        run: terraform validate

      # checks the format of the terraform
      - name: Terraform format
        run: terraform fmt -recursive -check

      # linting for terraform tool install
      - name: Install tflint
        run: | 
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Lint Terraform code
      - name: Run tflint
        run: tflint

      # Terraform Plan (dry run)
      - name: Terraform Plan
        run: terraform plan \
            --var "vpn_ip=${{ secrets.VPN_IP }}" \
            --var "app-branch=test" \
            --var "environment=${{ github.ref_name }}" \
            --input=false \
            --out terraform-plan

